export const BOTAO_CLICADO_SUCCESS = 'BOTAO_CLICADO_SUCCESS';
export const BOTAO_CLICADO_REQUEST = 'BOTAO_CLICADO_REQUEST';
export const BOTAO_CLICADO_FAILURE = 'BOTAO_CLICADO_FAILURE';

export const LOGIN_SUCCESS = 'BOTÃO_CLICADO_SUCCESS';
export const LOGIN_REQUEST = 'BOTÃO_CLICADO_REQUEST';
export const LOGIN_FAILURE = 'BOTÃO_CLICADO_FAILURE';

export const REGISTER_SUCCESS = 'BOTÃO_CLICADO_SUCCESS';
export const REGISTER_REQUEST = 'BOTÃO_CLICADO_REQUEST';
export const REGISTER_FAILURE = 'BOTÃO_CLICADO_FAILURE';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
